// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
)

type Event struct {
	ID          int64
	AuthorID    sql.NullInt64
	Name        string
	Date        sql.NullTime
	Location    string
	Description string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Order struct {
	ID         int64
	CustomerID sql.NullInt64
	Total      sql.NullInt32
}

type OrderDetail struct {
	ID        int64
	OrderID   sql.NullInt64
	TicketID  sql.NullInt64
	Price     sql.NullInt32
	Qty       sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Ticket struct {
	ID        int64
	EventID   sql.NullInt64
	Name      string
	Amount    sql.NullInt32
	Price     sql.NullInt32
	Status    sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID            int64
	WalletAddress string
	Name          string
	AvatarUrl     string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}
